export const TOGGLE_FORM = 'TOGGLE_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const OPEN_FORM = 'OPEN_FORM'
export const SEARCH_ITEM = 'SEARCH_ITEM'
export const ORDER_ITEM = 'ORDER_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const GET_VALUE_IS_SELECTED = 'GET_VALUE_IS_SELECTED'
export const RESET_IS_SELECTED = 'RESET_IS_SELECTED'


export const LIST_PRODUCT = 'LIST_PRODUCT'
export const BUY_PRODUCT = 'BUY_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const CHANGE_NOTIFY = 'CHANGE_NOTIFY'


